# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  slack_url = "<INSERT_YOUR_SLACK_WEBHOOK>"

  desc "Do Integration Tests on CircleCI"
  lane :integration_tests do
    # Run all Tests
    sh('cd .. && ./gradlew app:connectedAndroidTest')
    # Run spesific Tests
    # sh('cd .. && ./gradlew app:connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.package=<INSERT_YOUR_TEST_PACKAGE_HERE(com.app.myapp.emulatortests)>')

end
